#Config.yml! here


site.locale: "en-GB"
title: Sarah Dalrymple
email: dalrymple.sarah@gmail.com
logo: "/assets/images/Kilda3.jpg"


description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'https://sarahdal.github.io/' # the base hostname & protocol for your site, e.g. http://example.com

github_username:  SarahDal
repository: SarahDal/www

# Build settings
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0" 

destination: docs

plugins:
- jekyll-feed
- jekyll-include-cache
#- jekyll-leaflet

plugins_dir: _plugins
safe: false

date_format: "%d %b %Y"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true

search: true

footer:
  links:
    - label: "mastodon"
      icon: "fab fa-mastodon"
      url: "https://ecoevo.social/@sarahdalgulls/"
      rel: "me"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/zooplanktonbears/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

maplibre:
  width:  600
  height: 400
  zoom:   10
  pmtiles: true
  style: false
  # if style is not set to an URL (Mapbox, MapTiler, OpenMapTiles), the following values are used
  sprite: /assets/maps/osm-liberty-sprites/osm-liberty
  glyphs: /assets/maps/fonts/{fontstack}/{range}.pbf
  layers: /assets/maps/OSM-Liberty-layers.json
  sources:
    openmaptiles: 
      type: vector
      url: pmtiles:///assets/maps/maptiler-osm-2020-02-10-v3.11-belgium_brussels.pmtiles
      attribution: © <a href='https://openstreetmap.org'>OpenStreetMap contributors</a>
    natural_earth_shaded_relief:
      attribution: Made with <a href='https://www.naturalearthdata.com/'>Natural Earth</a> data
      maxzoom: 6
      type: raster
      url: pmtiles:///assets/maps/natural_earth_2_shaded_relief.raster.pmtiles
      # uncomment tileSize and tiles for cloud CDN tiles
      # tileSize: 256
      # tiles:
      #   - "https://klokantech.github.io/naturalearthtiles/tiles/natural_earth_2_shaded_relief.raster/{z}/{x}/{y}.png"


